name: Push esp-nn to IDF Component Registry

on:
  push:
    branches:
      - master

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload esp-nn to IDF Component Registry
        uses: espressif/upload-components-ci-action@v1
        with:
          namespace: "espressif"
          name: "esp-nn"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
